level_map = [
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                           XXXXXXXXXXX                          ',
'                                                                ',
'                                                                ',
'               XXXXXXXXX                 XXXXXXXXX              ',
'                                                                ',
'                                                                ',
'                                                                ',
'       XXXXXXXX                                   XXXXXXXX      ',
'               XX                               XX              ',
'                XX                             XX               ',
'                 XX                           XX                ',
'                 XXXXXXXXXX           XXXXXXXXXX                ',
'                                                                ',
'                                                                ',
'                              XXXXX                             ',
'                              XXXXX                             ',
'                              XXXXX                             ',
'                                                                ',
'          X      XXXXXXXXXXX         XXXXXXXXXX      X          ',
]

level_map2 = [
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',
'                               XXXX                            ',
'                           XXXX    XXXX                         ',
'                       XXXX            XXXX                     ',
'                   XXXX                    XXXX                 ',
'               XXXX                            XXXX             ',
'           XXXX                                    XXXX         ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'       XXXX                                            XXXX     ',
'           XXXX                                    XXXX         ',
'               XXXX                            XXXX             ',
'                   XXXX                    XXXX                 ',
'                       XXXX            XXXX                     ',
'                           XXXX    XXXX                         ',
'                               XXXX                             ',
'                                                                ',
'                                                                ',
'                                                                ',
'                                                                ',

]

tile_size = 24
screen_width = 1540
screen_height = len(level_map) * tile_size

